# 数据源配置
spring:
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        # 主库数据源
        mysql:
          url: jdbc:mysql://127.0.0.1:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: bilibili
          password: bilibili
          driver-class-name: com.mysql.cj.jdbc.Driver