# 开发环境配置
server:
  # 服务器的HTTP端口
  port: 8980

spring:
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379
    password: mesmart#mesmart
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

  # Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# 项目相关配置
ruoyi:
  profile: /home/bilibili/bilibili_admin_upload

